# Generated by Django 4.1.1 on 2022-09-08 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11)),
                ('senha', models.CharField(max_length=8)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.IntegerField()),
                ('tipo', models.IntegerField()),
                ('idade', models.IntegerField()),
            ],
        ),
    ]
