# Generated by Django 4.1.1 on 2022-09-08 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maquinas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('maquina', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('idfun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcionarios.funcionarios')),
            ],
        ),
    ]
